# Generated by Django 5.2.4 on 2025-07-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_ngo_authorized_person_id_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngo',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='approved',
        ),
    ]
