# Generated by Django 5.2.4 on 2025-07-24 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ngo_approved_remove_restaurant_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_claimed', models.PositiveIntegerField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('food_packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.foodpacket')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ngo')),
            ],
        ),
    ]
